"""add authentication fields to user

Revision ID: a43bf4535653
Revises: 7f517faa20ed
Create Date: 2026-07-30 14:57:41.083408

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a43bf4535653"
down_revision: str | Sequence[str] | None = "7f517faa20ed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "users",
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
    )

    op.add_column(
        "users",
        sa.Column("is_active", sa.Boolean(), nullable=False),
    )

    op.add_column(
        "users",
        sa.Column("is_verified", sa.Boolean(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_verified")
    op.drop_column("users", "is_active")
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
